- emulsion.fsproj
I've just published the new version of SharpXMPP to NuGet, and used it here.
That new version includes fix for the issue https://github.com/vitalyster/SharpXMPP/issues/15. Emulsion bot wasn't able to connect to our own XMPP server due to that bug.
Now it can connect to our server; I've verified that fact.
> #7: update SharpXMPP dependency

- .travis.yml
- Readme.md
- appveyor.yml
- emulsion.fsproj
Closes #5.
Also chose to update to .NET Core 2.0, because it's easier to run tests and redistribute.
> Update to .NET Core 2, enable CI

- .gitignore
- Emulsion.Tests/Actors/Core.fs
- Emulsion.Tests/Actors/Telegram.fs
- Emulsion.Tests/Actors/Xmpp.fs
- Emulsion.Tests/Emulsion.Tests.fsproj
- Emulsion.Tests/Telegram.fs
- Emulsion.Tests/Xmpp/SharpXmppHelper.fs
- Emulsion/Actors/Core.fs
- Emulsion/Actors/Xmpp.fs
- Emulsion/AssemblyInfo.fs
- Emulsion/Emulsion.fsproj
- Emulsion/Message.fs
- Emulsion/Program.fs
- Emulsion/Telegram.fs
- Emulsion/Xmpp/SharpXmppHelper.fs
Closes #20.
Also introduces a small cleanup in our Telegram client code (removes the unnecessary test commands).
> Pass Telegram user names to XMPP

- Emulsion.Tests/Actors/Telegram.fs
- Emulsion.Tests/Emulsion.Tests.fsproj
- Emulsion.Tests/MessageSenderTests.fs
- Emulsion.Tests/MessageSystem.fs
- Emulsion.Tests/MessageSystemTests.fs
- Emulsion/Actors/Telegram.fs
- Emulsion/Emulsion.fsproj
- Emulsion/MessageSender.fs
- Emulsion/MessageSystem.fs
- Emulsion/Program.fs
- Emulsion/Telegram/Client.fs
- Emulsion/Telegram/Funogram.fs
> Message system implementation for Telegram

- Emulsion/Emulsion.fsproj
- Emulsion/MessageSystem.fs
- Emulsion/Xmpp/Client.fs
- Emulsion/Xmpp/XmppClient.fs
This PR updates the SharpXMPP library to the newly released version 0.0.2.
In that release, I've fixed a couple of bugs, and the library API has been updating.
Impact:
- closes #41 (because of https://github.com/vitalyster/SharpXMPP/pull/22)
- closes #42 (because the API no more uses an `async void` horror from C#)
- somewhat improves the situation around #55 (throws proper exceptions when the client is know to be inactive instead of losing the messages)
- will improve the SharpXMPP error logging after we implement #16 (because of proper inner exception handling)
> Fix the XMPP reconnection issues

- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/Telegram/Client.fs
- Emulsion/Telegram/Funogram.fs
Closes #49.
There's a whole bunch of various corner cases and invalid markup types that may come from the Telegram server, and I've tried to handle them all properly.
We'll also log all the incoming Telegram messages.
> Convert links from Telegram

- Emulsion.Tests/Actors/Core.fs
- Emulsion.Tests/Actors/Telegram.fs
- Emulsion.Tests/Actors/Xmpp.fs
- Emulsion.Tests/Emulsion.Tests.fsproj
- Emulsion.Tests/Logging.fs
- Emulsion.Tests/MessageSenderTests.fs
- Emulsion.Tests/MessageSystemTests/MessageSystemBaseTests.fs
- Emulsion.Tests/MessageSystemTests/WrapRunTests.fs
- Emulsion.Tests/Settings.fs
- Emulsion.Tests/TestUtils/LockedBuffer.fs
- Emulsion.Tests/TestUtils/Logging.fs
- Emulsion.Tests/TestUtils/Waiter.fs
- Emulsion/Emulsion.fsproj
- Emulsion/MessageSender.fs
- Emulsion/MessageSystem.fs
Closes #66.
The `MessageSender` is now slightly aware of the `MessageSystem` state and won't try to send any messages while it isn't ready to accept them.
For now, the new concept is already used when the message system is restarting, but we will do more in scope of #18.
I've also rearranged some bits of our test code to reuse them in multiple tests.
> MessageSender now supports two stages of MessageSystem work

- Emulsion.Tests/MessageSenderTests.fs
- Emulsion.Tests/TestUtils/Waiter.fs
- Emulsion/MessageSender.fs
I had to reformat the test code because it is now a class (to inject the `ITestOutputHelper` instance). Only the two last tests were added in this PR.
Also, I've found that one of the test methods for the `MessageSender` was lacking the `Fact` attribute, so I've added it, too.
This PR fixes the queue logic: now it will only block on the incoming messages if it has nothing better to do (e.g. to deliver some queued messages). One of the new test verifies that behavior, and the other one verifies that the `SetReceiveStatus` of `false` will have a top priority and block delivering any messages even if they were queued beforehand.
Closes #82.
> Update the queue code in the MessageSender

- Emulsion.Tests/SettingsTests.fs
- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/EmulsionSettings.fs
- Emulsion/Telegram/Funogram.fs
- emulsion.example.json
Closes #85.
Aside from adding the filter, I've also defined a proper group id type in the configuration, since we want to compare it with the actual group id received from the server.
> Add group id filtering for Telegram

- Emulsion/Emulsion.fsproj
This will fix the JID parsing issues. Thanks to @gsomix for fixing SharpXMPP!
> Update SharpXMPP to 0.0.3

- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/Telegram/Funogram.fs
Closes #26 
Unresolved questions:
1. Should we support content of any type, not only images?
1. How to format messages and links?
1. Are there any methods to get links that can be opened in Russia?
@ForNeVeR @Minoru What do you think? Thanks!
> Translate photos from Telegram as links

- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/Telegram/Funogram.fs
> Remove message about unavailable link

- Emulsion.Tests/Emulsion.Tests.fsproj
- Emulsion.Tests/SettingsTests.fs
- Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
- Emulsion.Tests/Xmpp/SharpXmppHelperTests.fs
- Emulsion.Tests/Xmpp/SharpXmppPingHandlerTests.fs
- Emulsion.Tests/Xmpp/XmppClientFactory.fs
- Emulsion.Tests/Xmpp/XmppClientRoomTests.fs
- Emulsion.Tests/Xmpp/XmppClientTests.fs
- Emulsion/Emulsion.fsproj
- Emulsion/Settings.fs
- Emulsion/Xmpp/EmulsionXmpp.fs
- Emulsion/Xmpp/SharpXmppClient.fs
- Emulsion/Xmpp/SharpXmppHelper.fs
- Emulsion/Xmpp/SharpXmppPingHandler.fs
- Emulsion/Xmpp/Types.fs
- Emulsion/Xmpp/XmppClient.fs
- Readme.md
- emulsion.example.json
This has been done according to the [XEP-0199: XMPP Ping](https://xmpp.org/extensions/xep-0199.html).
The original idea (that should work, theoretically) is for bot to ping itself in the room (i.e. to ping its room "avatar", `room@conference.server.com/myBotNickname`).
Closes #88 (because it finishes the work on that issue).
**TODO**:
> #88: XMPP Ping

- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/Telegram/Funogram.fs
@noktoborus asked me to put *two* newlines in between the quote and message, presumably so it's easier to tell them
apart: https://codingteam.org.ru/_logs/codingteam%40conference.jabber.ru/2020/12/28.html#14:18:21.504544 I think the bot
should do the same, hence this commit.
> Add empty line after the quote

- Emulsion/Xmpp/XmppClient.fs
That API is dangerous (it may crash the process if misused).
While we seem to use it very carefully, I prefer to not take any chances.
> XmppClient: get rid of Async.Start

- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion.sln.DotSettings
- Emulsion/Telegram/Client.fs
- Emulsion/Telegram/Funogram.fs
Closes #133.
Turns out we weren't processing Telegram server errors properly: we were just logging them instead of throwing them to the message system (so it would know that the message wasn't delivered and start throttling it).
> Telegram error processing

- CHANGELOG.md
- Emulsion/MessageSender.fs
After reading the [F# Async Guide](https://medium.com/@eulerfx/f-async-guide-eb3c8a2d180a), I've found that we may miss errors in our mailboxes. Yes, our mailbox code is written in a pretty robust way and shouldn't ever trigger the `Error` event, but what if it isn't? Who really knows? We'll start logging these events and will see if that is the case.
> MessageSender: process Error events

- CHANGELOG.md
- Emulsion.Tests/SettingsTests.fs
- Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
- Emulsion/Emulsion.fsproj
- Emulsion/Settings.fs
- Emulsion/Xmpp/EmulsionXmpp.fs
- README.md
- emulsion.example.json
> Add XMPP connection timeout

- Emulsion.Tests/Actors/Core.fs
- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion/Actors/Core.fs
- Emulsion/Message.fs
- Emulsion/Telegram/Funogram.fs
> (#145) Core: move Telegram-related logic to the Funogram module

- Emulsion.sln
No idea why they were here. We only build/test for "Any CPU".
> Solution: get rid of redundant platforms

- CHANGELOG.md
- Emulsion.Web/HistoryController.fs
They already work that way according to [the spec](https://www.sqlite.org/queryplanner.html), though I'd like to make the code more clear.
Also, this will allow us to have stable order if we ever switch the database provider.
I wish it'd be possible to sort by the message datetime, but EFCore doesn't seem to support that for SQLite.
> Stable sort for messages

- .github/workflows/main.yml
- CHANGELOG.md
- Dockerfile
- Emulsion.ContentProxy/Emulsion.ContentProxy.fsproj
- Emulsion.Database/Emulsion.Database.fsproj
- Emulsion.MessageArchive.Frontend/Emulsion.MessageArchive.Frontend.proj
- Emulsion.Messaging/Emulsion.Messaging.fsproj
- Emulsion.Settings/Emulsion.Settings.fsproj
- Emulsion.Telegram/Emulsion.Telegram.fsproj
- Emulsion.Telegram/Funogram.fs
- Emulsion.Telegram/LinkGenerator.fs
- Emulsion.TestFramework/Emulsion.TestFramework.fsproj
- Emulsion.Tests/Emulsion.Tests.fsproj
- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion.Tests/Telegram/LinkGeneratorTests.fs
- Emulsion.Web/Emulsion.Web.fsproj
- Emulsion/Emulsion.fsproj
- Emulsion/Xmpp/XmppMessageSystem.fs
- README.md
> Prepare for the next Funogram update

- CHANGELOG.md
- Emulsion.Telegram/Client.fs
> Telegram.Client: log errors happened during the message queue processing

- Emulsion.Tests/LoggingTests.fs
Otherwise, concurrent tests could log something else and break our assertions.
> LoggingTests: add filter for test category

- Emulsion.TestFramework/Emulsion.TestFramework.fsproj
- Emulsion.TestFramework/Signals.fs
- Emulsion.Tests/MessagingCoreTests.fs
- Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
- Emulsion.Tests/Xmpp/XmppClientRoomTests.fs
Hopefully should fix #187 and fix #220.
My current hypothesis is that the tests experience timeout problems because of too much happening in parallel on the agents. I have even reproduced one failure locally.
After these improvements, I didn't reproduce any problems so far. We'll see how it'll behave.
Another issue is that our ping locator pattern was to "wait for X ms and then check if we receive all the expected messages". I have updated that to await the message asynchronously: this allows us to extend the waiting timeout without hurting the total test duration in the happy case.
> Improve test stability

- .github/workflows/release.yml
- .idea/.idea.Emulsion/.idea/dictionaries/fried.xml
- Emulsion/Emulsion.fsproj
- README.md
In addition to Docker, we'll start publishing Emulsion as framework-dependent app (meaning it's possible to run using an external `dotnet` installation).
> CI: publish as a framework-dependent app

- .github/workflows/main.yml
- .github/workflows/release.yml
We have `*.proj` as well as `*.fsproj`.
> CI: enumerate all project files when calculating caching policy

- CHANGELOG.md
- Emulsion.Telegram/Funogram.fs
- Emulsion.Tests/Telegram/FunogramTests.fs
> Telegram: support new quotes

- Emulsion.Tests/MessagingCoreTests.fs
- Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
Closes #242, also puts back the original timeout for `EmulsionXmppTests`.
> Test improvements

- Emulsion.Telegram/Funogram.fs
- Emulsion.Tests/Telegram/FunogramTests.fs
- Emulsion.Tests/Xmpp/SharpXmppHelperTests.fs
- Emulsion/Xmpp/SharpXmppHelper.fs
> Pass corrected Unicode to XMPP
