codingteam/emulsion

.gitmodules
Program.fs
Router.fs
Telegram.fs
emulsion.fsproj

#2: add initial Telegram support

---

.gitignore
EmulsionSettings.fs
Program.fs
Readme.md
Robot.fs
SharpXmppHelper.fs
Telegram.fs
emulsion.example.json
emulsion.fsproj

Add configuration support

---

Emulsion.Tests/Emulsion.Tests.fsproj
Emulsion.Tests/Xmpp/SharpXmppHelper.fs
Emulsion.Tests/Xmpp/XmppMessageFactory.fs
Emulsion/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/XmppClient.fs

Ignore historical messages

---

Emulsion.Tests/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/SharpXmppHelper.fs

Fix the namespace for message body

---

.dockerignore
.gitignore
Dockerfile
Readme.md
docker-compose.yml

Docker support

---

Emulsion.Tests/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/XmppClient.fs

Ignore empty XMPP messages

---

Emulsion.Tests/Xmpp/SharpXmppHelper.fs
Emulsion.Tests/Xmpp/XmppMessageFactory.fs
Emulsion/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/XmppClient.fs

Filter error messages from server

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Add support for Telegram forwarded messages

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Add sticker support

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Proper handling for multiline forwarded messages

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Formatting of replies to bot messages

---

.travis.yml
Dockerfile
Emulsion.Tests/Actors/Telegram.fs
Emulsion.Tests/Actors/Xmpp.fs
Emulsion.Tests/Emulsion.Tests.fsproj
Emulsion.Tests/MessageSystemTests/MessageSystemBaseTests.fs
Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion.Tests/TestUtils/LockedBuffer.fs
Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
Emulsion.Tests/Xmpp/XmppClientFactory.fs
Emulsion/Emulsion.fsproj
Emulsion/Logging.fs
Emulsion/MessageSystem.fs
Emulsion/Telegram/Client.fs
Emulsion/Xmpp/SharpXmppClient.fs
Emulsion/Xmpp/XmppMessageSystem.fs
License.md
Readme.md
appveyor.yml

We'll wait a couple of days for the editor integration (otherwise it's too hard for me to work on the F# 4.7 code).
**TODO:**

Migrate to .NET Core 3.0 / F# 4.7

---

Emulsion.Tests/MessageSystemTests/MessageSystemBaseTests.fs

Add SpinWait to test

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Emulsion.fsproj
Emulsion/Telegram/Client.fs
Emulsion/Telegram/Funogram.fs

Read captions for files from Telegram

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Read messages about new and left users

---

Emulsion.Tests/Actors/Core.fs
Emulsion.Tests/Actors/Telegram.fs
Emulsion.Tests/Actors/Xmpp.fs
Emulsion.Tests/MessageSenderTests.fs
Emulsion.Tests/MessageSystemTests/MessageSystemBaseTests.fs
Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
Emulsion.Tests/Xmpp/SharpXmppHelperTests.fs
Emulsion/Message.fs
Emulsion/Telegram/Funogram.fs
Emulsion/Xmpp/EmulsionXmpp.fs
Emulsion/Xmpp/SharpXmppHelper.fs

Improve messages about new and left users

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Message.fs
Emulsion/Telegram/Funogram.fs

Translate replies to join messages

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Translate stickers to XMPP as links

---

Emulsion.Tests/Xmpp/XmppClientTests.fs
Emulsion/Xmpp/SharpXmppHelper.fs

Closes #105
... and probably #88?

Recognize errors in XMPP messages

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Emulsion.fsproj
Emulsion/Telegram/Funogram.fs

Closes #112 
- Update Funogram to fix #112
- Add preview links for animations
- Add links for messages of unrecognized type

Update Funogram and add minor features

---

Emulsion.Tests/MessageSenderTests.fs
Emulsion.Tests/SettingsTests.fs
Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
Emulsion.Tests/Xmpp/XmppClientTests.fs
Emulsion.sln.DotSettings
Emulsion/Emulsion.fsproj
Emulsion/EmulsionSettings.fs
Emulsion/Xmpp/EmulsionXmpp.fs
Emulsion/Xmpp/XmppClient.fs
Emulsion/Xmpp/XmppMessageSystem.fs
emulsion.example.json

Add XMPP message timeouts

---

Emulsion.Tests/SettingsTests.fs
Emulsion.Tests/Xmpp/EmulsionXmppTests.fs
Emulsion.Tests/Xmpp/XmppClientFactory.fs
Emulsion.Tests/Xmpp/XmppClientTests.fs
Emulsion/Emulsion.fsproj
Emulsion/EmulsionSettings.fs
Emulsion/Xmpp/EmulsionXmpp.fs
Emulsion/Xmpp/SharpXmppClient.fs
Emulsion/Xmpp/SharpXmppHelper.fs
Emulsion/Xmpp/Types.fs
Emulsion/Xmpp/XmppClient.fs
emulsion.example.json

This is a quick fix I had to do before ICFPC. Probably this bot version will stay until 2020-07-21 on our secondary server.

Support password-protected XMPP rooms

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Telegram/Funogram.fs

Not limit forwarded messages

---

Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion/Emulsion.fsproj
Emulsion/Telegram/Funogram.fs

Send forwards from hidden users and channels

---

Emulsion.Tests/SettingsTests.fs

While looking to improve our settings parsing code, the only improvement I was able to make was to add this test :)

Settings: add a test for extended configuration read

---

CHANGELOG.md
Emulsion.Settings/Settings.fs
Emulsion.Telegram/Emulsion.Telegram.fsproj
Emulsion.Telegram/Funogram.fs
Emulsion.Tests/SettingsTests.fs
Emulsion.Tests/Telegram/FunogramTests.fs
Emulsion.Tests/Telegram/LinkGeneratorTests.fs
README.md
emulsion.example.json

(#170) Topics

---

Emulsion.Telegram/LinkGenerator.fs
Emulsion.Tests/Telegram/LinkGeneratorTests.fs

(#169) Proper MIME-type for stickers

---

.config/dotnet-tools.json
.github/workflows/main.yml
CHANGELOG.md
Directory.Build.props
Dockerfile
Emulsion.ContentProxy/Emulsion.ContentProxy.fsproj
Emulsion.Database/Emulsion.Database.fsproj
Emulsion.MessageArchive.Frontend/Emulsion.MessageArchive.Frontend.proj
Emulsion.Messaging/Emulsion.Messaging.fsproj
Emulsion.Settings/Emulsion.Settings.fsproj
Emulsion.Telegram/Emulsion.Telegram.fsproj
Emulsion.TestFramework/Emulsion.TestFramework.fsproj
Emulsion.Tests/Emulsion.Tests.fsproj
Emulsion.Web/Emulsion.Web.fsproj
Emulsion/Emulsion.fsproj
README.md

Update to .NET 8

---

Emulsion.Tests/Xmpp/XmppClientRoomTests.fs

Should improve test stability.

(#242) XMPP: migrate IQ tests to channels

---

.github/workflows/docker.yml
Emulsion.sln
scripts/Get-Version.ps1

General approach copied from https://github.com/ForNeVeR/fornever.me
Hopefully, closes #256.

CI: fix Docker tagging
